### ISSUE TITLE
Add better cache controls

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#100]
As @SDavisMedia learned while testing, caching can be a pain in the ass. While I added it for a good reason, there's also good reasons you might want to remove or adjust caching. Let's add the following:

- [x] Add a `Purge Cache` button in the settings panel
- [x] Add a `Clear from cache` button in the FD meta box in downloads if a cached file exists
- [x] Add an option to disable cache altogether

**Comment by pippinsplugins** [comment]
What specifically is being cached?

**Comment by ghost1227** [comment]
It caches remotely hosted files (they have to be stored locally to be able to be compressed) and it temporarily caches compressed zips when they're made.

**Comment by SDavisMedia** [comment]
The **Purge Cache** button definitely works.

The tooltip for **Purge Cache** says "effect" instead of "affect" ... simple typo.

I am not able to get **Disable Cache** to work. I monitor my FD cache folder and it continuously caches the files. Is it supposed to not cache at all, or simply not use the cached items for new "purchases"?

Also, there's a more serious issue and I'm not sure if it's related. I'm testing with a file on Amazon and then additional files in my media library. I add and remove the local files just to test purchases and see the difference in auto download files included in the zip, so I know if I'm getting a cached copy or not. After several tests, I ended up removing all local files from the product leaving nothing but the Amazon file. I tested another purchase and was met with:

![image 2016-10-06 at 2 34 16 pm](https://cloud.githubusercontent.com/assets/2359131/19171513/11b17dd8-8bd2-11e6-99e7-018e25288ebd.png)

**Comment by ghost1227** [comment]
Disable Cache probably _is_ working... just not how you expect. I can't actually delete the local copies of the files after processing a download - the download function exits and anything after it doesn't run (part of how EDD core handles downloads). As a result, the Disable Cache option deletes files at the _beginning_ of the processing stage instead of the end. with Disable Cache enabled, the first thing that happens when you go to download a file is it checks for a local copy and, if one is found, immediately deletes and re-downloads it.

I'll take care of the tooltip typo... I've made that particular mistake a million times.

Not sure what's you're getting at with the third comment though... however, I _can_ tell you that there's no situation in FD that should ever result in a URL that looks like that.

**Comment by SDavisMedia** [comment]
@ghost1227 I'll test cache disabling again with that in mind. I can test purchases that should have different contents in the auto downloaded zip to see if it is in fact deleting the cached copy and replacing it with a new one of the same name.

For the 404 issue, please try to replicate. It downloads the file from Amazon just fine in any other scenario and it downloaded it just fine before I started adding additional local files. It wasn't until I add local files, did some tests, then removed those local files from the download leaving nothing but the Amazon file that it started happening.

**Comment by ghost1227** [comment]
Typo fixed... just to make sure I'm understanding, the steps to replicate are

1. Add a single file from Amazon S3 to a download
2. Download the file
3. Add a few local files to the download
4. Download the file
5. Remove _all_ local files (so just the S3 file is left)
6. Download the file

where step 6 is the one that's failing for you?

**Comment by ghost1227** [comment]
@SDavisMedia ^

**Comment by SDavisMedia** [comment]
@ghost1227 Correct. Keep in mind that I didn't test that on purpose. Those are just the steps I feel are relevant based on the tests I've done.

**Comment by ghost1227** [comment]
ok

**Comment by SDavisMedia** [comment]
@ghost1227 Okay yup cache disabling is all good. I tested by adding a new file to the product and making a new purchase. Then checking the auto downloaded zip to make sure its content changed. All is well.

That said, after doing the above three times, resulting in a total of four files on the product, I remove the three local ones from the product and tried again. Same result... auto downloading just the Amazon file resulted in 404.

**Comment by ghost1227** [comment]
I'm testing now

**Comment by ghost1227** [comment]
@SDavisMedia Does it specifically happen with auto download?

**Comment by SDavisMedia** [comment]
@ghost1227 That's all I've tested so far.

**Comment by SDavisMedia** [comment]
All good now! :+1:
