### ISSUE TITLE
Free Download Status Required

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-free-downloads#128]
I run a website that offers a 50/50 mix of free and paid products using EDD. While the Free Downloads plugin is great for handling the email collection and download functionality, if your site is receiving thousands of free downloads a day, the payment records quickly get out of control and it's hard to manage (or find) legit payment records.

Much like the "Test Payments" functionality within EDD, it would be a great if a new EDD Status was created specifically for the EDD Free Downloads plugin. Within the plugin settings a default behaviour option could be added to ignore these records when viewing the payment history. A new "Free Downloads" tab would be added along with the other statuses to allow you to view these records should you wish in a filtered fashion.

**Comment by cklosowski** [comment]
I'm not sure I agree with a whole new 'status' for these payments. That would pose some serious issues with lots of other extensions needing to update in order to accommodate the 'free_download' status for things like licenses, etc.

I think, like we did with the 'gateway' and 'software licensing' filters. We could add a new filter in for 'non-free' or some other wording, that would eliminate payments that are for $0.

**Comment by cklosowski** [comment]
I've been thinking on this throughout the day. I think it'd be best to do this in EDD Core. I'm thinking an 'Advanced Filters' section in the row (it's starting to get cluttered with other add-ons) here:
![screen shot 2017-10-18 at 3 32 36 pm](https://user-images.githubusercontent.com/1390124/31745921-9bbd0554-b419-11e7-98db-b88ca7dfed61.png)

**Comment by cklosowski** [comment]
I've opened this issue up on EDD Core to see if we can get something worked up for this: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6086
