### ISSUE TITLE
File downloads fail on mobile when product has variable prices and file is assigned to price

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#163]
File downloads fail on mobile when the following conditions are true:

- variable prices enabled
- file assigned to specific price
- price option is free

Disabling variable prices fixes the issue.

See https://secure.helpscout.net/conversation/374970730/60426/?folderId=180505

**Comment by SDavisMedia** [comment]
I believe I've replicated this. On mobile (Android), I get this using the steps above:

<img width="638" alt="screenshot 2017-09-05 13 52 52" src="https://user-images.githubusercontent.com/2359131/30083320-ded75c66-9242-11e7-90e3-496605bad806.png">

Like @pippinsplugins said, the download works fine when variable pricing is disabled.

The problem is I can still replicate on `issue/163`. I get the same behavior on that branch and on `master`.

**Comment by ghost1227** [comment]
Can you post more info on your setup? I've been unable to reproduce it since `issue/163`. (also, could be cache related... there was a TON of updated JS for this one)

**Comment by SDavisMedia** [comment]
@ghost1227 let me know what you'd like to see specifically. Settings or just general info?

**Comment by ghost1227** [comment]
Settings and screenshot of the download config for that product

**Comment by SDavisMedia** [comment]
@ghost1227 here ya go

<img width="1026" alt="screenshot 2017-09-05 16 50 45" src="https://user-images.githubusercontent.com/2359131/30088388-d7a6c432-925a-11e7-93d4-30ac747d0dc3.png">
<img width="1102" alt="screenshot 2017-09-05 16 53 47" src="https://user-images.githubusercontent.com/2359131/30088393-dbe75a84-925a-11e7-91a0-8081b0cf05c6.png">

**Comment by ghost1227** [comment]
@SDavisMedia Repull and test again please.

**Comment by SDavisMedia** [comment]
@ghost1227 Fixed! :+1:

**Comment by SDavisMedia** [comment]
@pippinsplugins can you test this as well?

**Comment by ghost1227** [comment]
Fixed merge conflict

**Comment by pippinsplugins** [comment]
All works well, merged!
