### ISSUE TITLE
Improve cache invalidation

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-free-downloads#188]
In #173, it was decided to not cache external files from Amazon S3 and Dropbox. We just ran into an issue on the RCP site of outdated files being delivered from wordpress.org due to the caching.

The outdated file was greater than 7 months old, so this has been going on for some time.

Is there any value in caching these download files? If the file is being hosted from remote, there's probably a reason the person wants it to be delivered from there.

**Comment by pippinsplugins** [comment]
Related #182 and #178

**Comment by pippinsplugins** [comment]
At minimum let's fix the bug that causes cached files to be delivered even when caching is disabled in settings.

**Comment by dannyb195** [comment]
Reproduced by:
1. Creating a multiple file download product with caching *on* (having an external file seem moot at this point)
2. Download the product to trigger the caching process
3. Go to Downloads > settings > extensions and selecting `disable cache`

The most direct solution would seem to be clear *all* cache on save is the `disable cache` option is set if it was not set previously.

**Comment by mindctrl** [comment]
Imagine a scenario where someone uses EDD Software Licensing readme.txt parsing to maintain changelog and version info on a download, and the file is hosted remotely. They don't need to regularly update the download since the version/changelog info is maintained during update checks, so you can't rely on `save_post` to clear the cache for that download.

Also consider that if someone is tracking the # of downloads based on the remote logging/stats, those numbers will not be correct since this plugin is caching them. In the example above, the RCP add-on download stats on wp.org are incorrect due to local caching.

I see two problems.

- Caches files even when disabled
- Seemingly has no way to check if a remotely hosted file has been updated (haven't looked at the code)

If someone does have caching enabled, there has to be a reliable method of checking if it's stale. There needs to be some kind of check that compares local to remote or checks to see if the version number stored by EDD has been updated since last cache.

For people who are already experiencing this bug, turning off the cache (after fixing the issue) isn't really an option as they'd have to be aware of the bug to turn it off. I think you'd also need to wipe the cache during the next update to ensure it works as expected going forward for people who leave it enabled, assuming you keep it around.

**Comment by cklosowski** [comment]
I think there is some value to the 'caching' option, and it's mostly in the case of using compression.

A few improvements I can think of would be to restrict the use of caching to when there are more than 1 file to deliver, so we're not continuously running the .zip functions on a group of files. That could be detrimental to their server's CPU, bandwidth, and if large enough disk space quotas.

This would all be null and void if we could count and rely on the `/tmp` being accessible by PHP, but I don't think that's feasible, so using the WordPress upload dirs is required. This means that if 100 download requests come in quickly, 3 files at 5MB would zip to just under 15MB (appox). So for 100 download requests were using that same 15MB of storage.

Now, if we were to zip that up every time, we're running the zip function 100 times, causing a file read of 300 times, 100 file write requests, and now (unless we write a cleanup script), leaving ~1500MB on the server.

While the cache usage should be limited, I think we can restrict it's usage to non-remote, multi-file delivery and be completely fine with it. But as soon as multiple files are being handled, I think caching is the only way to go. Further more we can also add a 'cache timeout' setting that let's users set a timeout on how often it should be cached. We can somehow use that setting in order to check the last time the file was updated, and re-create it if needed.

**Comment by cklosowski** [comment]
To outline the changes I believe would make the most sense here @dannyb195 
1) Add an option in the cache settings (only visible when caching is available) allowing the store owner to set the number of hours for the cached files to exist.
2) Only apply the caching when the files are not local _AND_ when multiple files exist. (if it's remote and/or is only one file, we shouldn't use the .zip caching)
3) With setting 1 above, we could check the last time the file was written when processing number 2 we can check the times.

**Comment by dannyb195** [comment]
got started before I saw your comment though work is happening at https://github.com/easydigitaldownloads/edd-free-downloads/tree/issue/188

**Comment by dannyb195** [comment]
@cklosowski after working on this for a bit I think we also need to write to the download post object as well as a timeout option.  Writing to the download post object will allow us to check the size of the zipped file thus being able to determine if remote files have changed.

**Comment by cklosowski** [comment]
@dannyb195  Just realized I contradicted myself in my last 2 comments. One says 'non remote' and the 2nd one says 'non local'.

Since stating the MD5 of a remote file negates the purpose of this whole MD5 thing since you'd have to pull down the file in general to MD5 is (causing the delay again while downloading it), thats whey the cache time is the most important.

A file size check could actually provide a false positive, i'd be best to run and MD5 on the .zip file, since you could in theory have made changes to the file but retained the exact file size. While unlikely the MD5 just stops that from happening all together.

If we go that route, we can just use the Post Meta of a download and the `update_meta` method. Let's have a quick chat tomorrow to kind of scope out what you are thinking for this.

**Comment by dannyb195** [comment]
@cklosowski  So the current status of https://github.com/easydigitaldownloads/edd-free-downloads/tree/issue/188 will recreate a zip file based upon a timeout (current using MINUTE_IN_SECONDS for testing). But yes lets chat today to rubber-duck this issue.

*Note* the mentioned branch is not merge / PR ready

**Comment by dannyb195** [comment]
PR in progress at https://github.com/easydigitaldownloads/edd-free-downloads/pull/216

**Comment by dannyb195** [comment]
On 10/25/2017 @cklosowski and I decided to go with a time based cache clearing option (defaulting to 1 hour) as well as a save_post action to clear individual zipped files for multi-file downloads.

**Comment by dannyb195** [comment]
PR at https://github.com/easydigitaldownloads/edd-free-downloads/pull/216

**Comment by cklosowski** [comment]
Ok this is working for me, some testing details:
* File time is defaulted to 1 hour. If you want to test it further you can replace the code that states file time + cache expiration setting with something like `file time + MINUTE_IN_SECONDS` for faster testing
* Upon saving a download, _all_ cached files for that download are deleted, as to support variable pricing and multi-purchase mode. (we are now making file names contain `bundle-<download_id>` so we can target them easily)

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs if you guys could put this through the wringer, that'd be awesome.
