### ISSUE TITLE
No customer attached to payment record with modal bypass

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#233]
I'd say this is a continuation of https://github.com/easydigitaldownloads/edd-free-downloads/issues/196#issuecomment-337034672 but deserving of a fresh issue.

If you have the modal bypass feature enabled and from a logged in account you attempt to download a file, the payment record is created but no customer record is attached to it and no email address is recorded. 

<img width="1343" alt="screenshot 2017-12-13 21 21 09" src="https://user-images.githubusercontent.com/2359131/33976693-952b30c2-e04b-11e7-8888-3e8e7dfa0106.png">

**Comment by SDavisMedia** [comment]
Oops, key detail here is that the logged in account **does not** already have a customer record. So you need to be logged into a WP user account that has never made a  purchase. Then you try to bypass the modal and download the product. The customer record is not created, and therefore not attached to the payment.

On those records, `_edd_payment_user_id` has a value of `0`.

**Comment by sunnyratilal** [comment]
PR: #235

**Comment by SDavisMedia** [comment]
@sunnyratilal This is properly creating the new customer but it looks to be using the customer's email address as both the first and last name. https://cl.ly/3O3e3R240G1T

When someone registers to the site using a form like `[edd_register]`, they aren't given first and last name fields. So this could be a common occurrence.

(If the first and last names are saved for the user before the free download, then they are properly used... I've confirmed)

**Comment by mintplugins** [comment]
Replicated what Sean found. Traced it back and it looks like EDD_Payment uses the email address for the name this if the name passed-in is blank:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/62a524c7b890d7daa57eab1921de938189d094f7/includes/payments/class-edd-payment.php#L2759-L2761

So that looks to be an issue with EDD Core, if that's something we think shouldn't happen. 

For this issue, everything works correctly in my tests! 👍
