### ISSUE TITLE
Doesn't work with Auto Register

### ISSUE THREAD

**Issue by MapSteps** [easydigitaldownloads/edd-free-downloads#238]
He guys,

I've just tested the new (2.2.1) version on one of my installs and figured it that no accounts get created using the Auto Register Plugin.

Best,
David

**Comment by pippinsplugins** [comment]
@MapSteps have you enabled the option to create accounts in Downloads > Settings > Extensions > Free Downloads?

**Comment by MapSteps** [comment]
Hey @pippinsplugins,

thanks for your reply! I think I'm missing something, the only option I got is to "Bypass Auto Registration".

**Comment by mintplugins** [comment]
I have replicated this issue. Auto register no longer registers users through Free Downloads. This is because Auto Register runs the `maybe_insert_user` function by hooking to the `edd_insert_payment` hook, which only runs during the `edd_insert_payment` function, which is a [legacy](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6325) function.

This will either have to be fixed in EDD core by [adding the edd_insert_payment hook to the EDD_Payment method](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5127), or fixed in Auto Register by hooking to an existing payment in the `EDD_Payment::insert_payment()` method  or `EDD_Payment::save()` method

**Comment by pippinsplugins** [comment]
Let's fix in FD by changing the hook used here.

**Comment by mintplugins** [comment]
@pippinsplugins I don't think we can fix it in Free Downloads without overhauling it to use the legacy function. But we can fix it in Auto Register by changing the hook there (I think that might be what you mean, but just confirming to be clear).

**Comment by pippinsplugins** [comment]
@mintplugins PR looks good (haven't tested yet). Ready for it to be tested?

**Comment by mintplugins** [comment]
@pippinsplugins PR has been tested and modified as per your review now

**Comment by pippinsplugins** [comment]
Merged!
