### ISSUE TITLE
Form Width

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/edd-free-downloads#51]
On mobile the form is full width, but the css includes iPads in mobile, and in that environment full width is too much.

**Comment by ghost1227** [comment]
The css isn't including iPads per se... I'm using a jQuery library to determine which version to use (the 'full-width' form isn't a full width form, it's actually a separate page). Currently, it's using `isMobile.any`. I did this because SOME tablets (including one of the ones I tested it on) don't look right when using the lightbox. Here's the library... https://github.com/kaimallea/isMobile

@topher1kenobe Take a look and lemme know if there's a subset that you think would be better than just forcing all mobile devices to use the separate page instead of lightbox (keeping in mind that not all tablets are created equal).
