### ISSUE TITLE
Bug when "Redirect to checkout" is checked

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#7]
RE: Ticket HS#10472

Not sure if you'd consider this a bug, but it baffled me for about 20 minutes. If you have "Immediately redirect to checkout after adding an item to the cart?" set on, and use Free Downloads, about 10 seconds after displaying the name/email popup, EDD redirects to the Checkout, which is empty. Probably should ignore that setting when displaying a free product with Free Downloads.

**Comment by mindctrl** [comment]
Just got a report of this.

**Comment by mindctrl** [comment]
Making a note to update this customer when this is fixed. https://secure.helpscout.net/conversation/96185157/10454/

**Comment by pippinsplugins** [comment]
Just had another confirmed report of this.

**Comment by ghost1227** [comment]
It's getting fixed today

**Comment by pippinsplugins** [comment]
:+1:

**Comment by ghost1227** [comment]
Fixed in 1.0.6

**Comment by pippinsplugins** [comment]
This isn't working still.

**Comment by pippinsplugins** [comment]
Is this the supposed fix for this? https://github.com/easydigitaldownloads/edd-free-downloads/commit/473469ccaa405648e679a0971505cbac2420de93

**Comment by pippinsplugins** [comment]
If so, that's a buy now button, not the JS redirect.

This issue is referring to this option:
![screen shot 2015-06-16 at 9 32 48 am](https://cloud.githubusercontent.com/assets/1034109/8185545/b25a7c6c-140a-11e5-8cfd-c753396692a8.png)

That is controlled via JS in EDD core: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/assets/js/edd-ajax.js#L169

I'm not immediately sure how to fix it but that commit above definitely won't do it.

**Comment by pippinsplugins** [comment]
Proposed solution: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3508

That will actually work without an changes to Free Downloads being made.

**Comment by pippinsplugins** [comment]
Ok closing this as fixed in EDD 2.4. No need for changes here.
